title: 4 programming languages you should learn
tagline: Take a tour of 4 popular programming languages and decide what you'll learn.
description: >-
  Getting started in programming can be overwhelming. What should you build
  first? Which programming language should you use? This course will help you
  take these important first steps. 
template:
  repo: hello-world-6-languages-template
  name: hello-world-6-languages
  description: Say Hello World! in 4 different programming languages
before:
  - type: createIssue
    title: Start Here! Introduction to programming languages
    body: new-issue.md
  - type: createPullRequest
    title: Say Hello World with HTML
    body: 01-html-intro.md
    head: add-html
    action_id: html_pr
  - type: createPullRequest
    title: Say Hello World with Javascript
    body: 01-javascript-intro.md
    head: add-javascript
    action_id: javascript_pr
  - type: createPullRequest
    title: Say Hello World with Python
    body: 01-python-intro.md
    head: add-python
    action_id: python_pr
  - type: createPullRequest
    title: Say Hello World with Ruby
    body: 01-ruby-intro.md
    head: add-ruby
    action_id: ruby_pr
  - type: closeIssue
    issue: '2'
  - type: closeIssue
    issue: '3'
  - type: closeIssue
    issue: '4'
  - type: closeIssue
    issue: '5'
steps:
  - title: What should you learn first?
    description: >-
      Learn about the role of programming languages and how they are used in
      real projects
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: octokit
        method: issues.update
        owner: '%actions.html-pr.data.head.repo.owner.login%'
        repo: '%actions.html-pr.data.head.repo.name%'
        number: '%actions.html-pr.data.number%'
        state: open
  - title: Say Hello World! with HTML
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    description: Most people learn HTML first. Find out why ...
    link: '{{ repoUrl }}/issues/2'
    event: push
